### ISSUE TITLE
[Android]Notification not show when the app is focus

### ISSUE THREAD

**Issue by t4kumj** [williamrijksen/com.williamrijksen.onesignal#23] opened 2017-02-17 06:29 UTC
I'm using titanium appcelerator 6.0.0 GA and the Notification not show when my app in focus.
Please give me example code to show it.
Thanks.

**Comment by chmiiller** [comment] 2017-02-17 08:57
Android or iOS?

**Comment by t4kumj** [comment] 2017-02-19 10:42
Android 6.0, thanks

**Comment by santhoshvkumar** [comment] 2017-05-09 12:16
For IOS I am facing the Same issue. 
`onesignal.addEventListener('notificationReceived', function() { alert ("msg");}`
but it call like couple of times after that there is no alert.

Not Sure what's the Root Cause. In Live mode EventListener Is getting called and it's working properly but in deployment it's not calling EventListener at all. Not sure what I am missing

**Comment by iAmBorn2Code** [comment] 2017-05-10 07:47
I'm having the same issue with 
iOS 10.3.1
6.0.3GA

In LIVE VIEW MODE - Working
DEVELOPMENT - Not Working.

**Comment by jkasten2** [comment] 2017-05-20 01:44
You could change the following line to always show a notification in the shade even when the app is in focus.
https://github.com/williamrijksen/com.williamrijksen.onesignal/blob/cb2a6b2074b1f6c6390571efa16e419fac08d367/android/src/com/williamrijksen/onesignal/ComWilliamrijksenOnesignalModule.java#L46

Change `None` to `Notification` to do this.

**Comment by jvandijk** [comment] 2017-08-09 12:18
We're currently using a strategy that allows users to create their own interaction based on the opened / receive events. The current default setting is to show no 'in app popup'.

**Comment by TheVisitorXX** [comment] 2017-08-13 18:26
I have the same issue, notificationReceived / notificationOpened aren't called when the app is in foreground/has focus. It's only called when the app is closed completely. It is working fine for Android but not for iOS.

**Comment by luiscript** [comment] 2019-05-29 18:56
I'm having a similar issue. During development on iOS if I'm debugging with --liveview, notification arrives normally, when app is focus and when is in background. 

But if I'm debugging without --liveview notification only arrives when apps is in background.

Any idea what's happening here? 

Thanks this is a great module, so easy to use. I hope this problem can be solved to use this in production.

**Comment by chmiiller** [comment] 2020-02-21 14:36
Hi everyone, is this still a valid issue on Android? Can you please confirm this @t4kumj ?
@luiscript I think you can create a separated issue here on the repo with more information on what's happening to you. I'm not using --liveview and I would not recommend using it to test push notification behavior while in development.
I'm closing this issue since it's been reported a long time ago and it doesn't seem to be an issue anymore. @t4kumj in case this is still happening, feel free to open a new one please =)
Thanks!

**Closed as completed by chmiiller** 2020-02-21 14:36 UTC
